"""Prints every number used in the paper with the result file and key it comes from (NUMBERS.md)."""
import json, numpy as np, os
L = lambda f: json.load(open(f))
out = ['# Numbers in the paper and where they come from', '', 'All paths are relative to `xcur/`. Regenerate with `python3 paper_numbers.py > ../NUMBERS.md`.', '']
def sec(t): out.extend(['', f'## {t}', '', '| Claim | Value | Source |', '|---|---|---|'])
def row(c, v, s): out.append(f'| {c} | {v} | `{s}` |')
D = L('results/v2/dose_summary.json')
sec('Prediction (Fig. 1, Sec. V)')
row('pairs tested', sum(d['n'] for d in D.values()), 'results/v2/dose_summary.json: sum of n')
for k, d in D.items():
    row(f'{k}: MAE (m_shared) / max error', f"{d['mae_shared']:.4f} / {d['max_shared']:.3f}", f'results/v2/dose_summary.json["{k}"]')
    row(f'{k}: recall measured / predicted at 0.7', f"{d['rec_obs']:.3f} / {d['rec_pred']:.3f}", f'results/v2/dose_summary.json["{k}"]')
    row(f'{k}: median m_doc / m_shared', f"{d['median_m_doc']:.3f} / {d['median_m_shared']:.3f}", f'results/v2/dose_summary.json["{k}"]')
    row(f'{k}: bound violations m_doc / m_shared', f"{d['viol_doc']} / {d['viol_shared']}", f'results/v2/dose_summary.json["{k}"] (boundary-equal pairs at J\'=0.7 counted as non-violations in text)')
sec('Pair recall (Table I)')
out.append('Generated by `tables_v3.py` from `results/v2/e1_gold_first_plain.json` (TAB P), `results/v2/f2_real.json` (TAB S, Enron S), `results/v2/e4_enron.json` + `results/v2/extra_cells.json` (Enron N), `results/v2/scale_ecthr.json`, `results/v2/scale_c4.json` (ECtHR S, Web S); key `results[strategy]["0.7"]["dup_recall"]`.')
for name in ('ecthr', 'c4'):
    f = f'results/v2/pipeline_{name}_plain.json'
    if not os.path.exists(f): continue
    R = L(f)
    sec(f'Pipeline recall and removals, {name} (Fig. 2c/d, Sec. V)')
    for s in ('RAW', 'MASK', 'SUR-DOC', 'SUR-CORPUS', 'HASH-ENTITY'):
        for b in ('28x4', '16x7', '14x8', '8x14', '7x16'):
            v = [R['results'][f'{s}|{sd}|{b}'] for sd in (0, 1, 2)]
            row(f'{s} {b}: removed mean [min,max]; recall mean [min,max]', f"{np.mean([x['removed'] for x in v]):.0f} [{min(x['removed'] for x in v)},{max(x['removed'] for x in v)}]; {np.mean([x['recall'] for x in v]):.3f} [{min(x['recall'] for x in v):.3f},{max(x['recall'] for x in v):.3f}]", f'{f}: results["{s}|seed|{b}"]')
    for s, b in R['boot'].items():
        row(f'{s} - RAW (seed 0, 14x8): d_removed [CI]; d_recall [CI]; added/restored', f"{b['d_removed']:+.0f} [{b['d_removed_ci'][0]:.0f},{b['d_removed_ci'][1]:.0f}]; {b['d_recall']:+.3f} [{b['d_recall_ci'][0]:.3f},{b['d_recall_ci'][1]:.3f}]; {b['added']}/{b['restored']}", f'{f}: boot["{s}"]')
sec('Placeholder merges (Table II)')
for k, v in L('results/v2/cboot_exact.json').items():
    row(f'{k}: RAW, MASK, +/-, diff [CI], clusters changed', f"{v['raw']}, {v['strat']}, {v['added']}/{v['restored']}, {v['diff']:+.0f} [{v['ci'][0]:.0f},{v['ci'][1]:.0f}], {v['clusters_changed']}", f'results/v2/cboot_exact.json["{k}"]')
for name in ('ecthr', 'c4'):
    f = f'results/v2/pipeline_{name}_datatrove.json'
    if os.path.exists(f):
        b = L(f)['boot']['MASK']; R = L(f)['results']
        row(f'{name} normalized: RAW, MASK, +/-, diff [CI]', f"{R['RAW|0|14x8']['removed']}, {R['MASK|0|14x8']['removed']}, {b['added']}/{b['restored']}, {b['d_removed']:+.0f} [{b['d_removed_ci'][0]:.0f},{b['d_removed_ci'][1]:.0f}]", f'{f}: boot["MASK"], results["RAW|0|14x8"]')
sec('Audit (Table III)')
for c, rows in L('results/v2/audit2_labels.json').items():
    for t, v in rows.items():
        if t == 'unique_records_audited':
            row(f'{c}: distinct records audited', v, f'results/v2/audit2_labels.json["{c}"]'); continue
        row(f'{c} {t}: n, audited, labels, median ID share of diffs vs survivor (Table III) / vs most similar record, Wilson CI of keep share', f"{v['n']}, {v['audited']}, {v['labels']}, {v['survivor_share_diff_in_ids_all']['median']:.2f} / {v['share_diff_in_ids_all']['median']:.2f}, {v['keep_share_ci']}", f'results/v2/audit2_labels.json["{c}"]["{t}"] (samples with full texts: results/v2/audit2_{c}.json; labels: audit2_labels.py, audit2_labels_c4.py)')
sec('Proposition condition check and prediction metrics (Sec. V, Fig. 1b)')
for k, v in L('results/v2/dose_c1_summary.json').items():
    row(f'{k}: n, MAE, max abs error', f"{v['n']}, {v['mae']}, {v['max']}", f'results/v2/dose_c1_summary.json["{k}"] (dose_check2.py; unit tests tests_prop/)')
dm = L('results/v2/dose_metrics.json')
for k in ('n', 'mae_shared', 'max_shared', 'disagree_theta_shared', 'disagree_theta_doc', 'bound_violations_shared'):
    row(k, dm[k], f'results/v2/dose_metrics.json["{k}"] (dose_metrics.py)')
for k, v in dm['warning_rule_on_raw_pairs'].items():
    row(f'warning rule m_doc > 0.176 on pairs RAW keeps at 0.7: {k}', v, 'results/v2/dose_metrics.json["warning_rule_on_raw_pairs"]')
sec('Scrubbing scope, Dolma-like (Sec. V)')
for name in ('ecthr', 'c4'):
    f = f'results/v2/pipeline_{name}_plain_narrow.json'
    R = L(f)
    for s_ in ('RAW', 'TYPE', 'SUR-DOC', 'HASH-ENTITY'):
        v = [R['results'][f'{s_}|{sd}|14x8'] for sd in (0, 1, 2)]
        row(f'{name} narrow {s_} 14x8: removed mean; recall mean; recall on copies whose original or copy has an identifier', f"{np.mean([x['removed'] for x in v]):.1f}; {np.mean([x['recall'] for x in v]):.4f}; {np.mean([x['recall_touched'] for x in v]):.4f} (n={R['n_copies_touched']})", f'{f}: results["{s_}|seed|14x8"]')
    for s_, b in R['boot'].items():
        row(f'{name} narrow {s_} - RAW (seed 0): d_recall [CI]', f"{b['d_recall']:+.4f} [{b['d_recall_ci'][0]:.4f},{b['d_recall_ci'][1]:.4f}]", f'{f}: boot["{s_}"]')
row('Docs with any narrow-scope identifier', 'ECtHR 614/12,999; web 7,541/94,293', 'results/v2/pipeline_{ecthr,c4}_narrow.log')
sec('Enron crossing (Sec. V)')
cx = L('results/v2/curves_exact.json')['Enron second-source|plain']
for s_, t in (('RAW', '0.9'), ('SUR-DOC', '0.55'), ('HASH-ENTITY', '0.6')):
    row(f'Enron S {s_} theta={t}: removed; pipeline recall', f"{cx[s_][t]['cases_lost']}; {cx[s_][t]['dup_recall_comp']}", f'results/v2/curves_exact.json["Enron second-source|plain"]["{s_}"]["{t}"]')
if os.path.exists('results/v2/enron_cross.json'):
    row('Enron crossing: removed sets', L('results/v2/enron_cross.json'), 'results/v2/enron_cross.json (enron_cross.py)')
sec('Other numbers in the text')
f2 = L('results/v2/f2_real.json')
row('Enron second-source pair recall MASK / RAW', f"{f2['Enron|plain']['results']['MASK']['0.7']['dup_recall']:.4f} / {f2['Enron|plain']['results']['RAW']['0.7']['dup_recall']:.4f}", 'results/v2/f2_real.json["Enron|plain"]')
row('SUR-CORPUS exposure precision/recall TAB', f"{L('results/v2/e1_gold_first_plain.json')['results']['SUR-CORPUS']['link_person']}", 'results/v2/e1_gold_first_plain.json results["SUR-CORPUS"]["link_person"]')
row('Detector coverage of gold identifier characters', f"{L('results/e3_tab.json')['quality']['char_recall']:.4f}", 'results/e3_tab.json quality.char_recall')
print('\n'.join(out))
